export const portfolioData = [
  {
    id: 1,
    type: "app",
    name: "Hair Care",
    projectType: "Service Provider",
    image: "/project1.jpg",
    color: "#b1b1b3",
  },
  {
    id: 2,
    type: "website",
    name: "Chez Tati",
    projectType: "E-Commerce",
    image: "/project2.jpg",
    color: "#f2ddce",
  },
  {
    id: 3,
    type: "app",
    name: "Pentagon Care",
    projectType: "Service Provider",
    image: "/project3.jpg",
    color: "#c7e0eb",
  },
  {
    id: 4,
    type: "website",
    name: "Jusbuy",
    projectType: "E-Commerce",
    image: "/project1.jpg",
    color: "#d1e0d1",
  },
  {
    id: 5,
    type: "app",
    name: "Chez Tati",
    projectType: "E-Commerce",
    image: "/project2.jpg",
    color: "#f2ddce",
  },
  {
    id: 6,
    type: "website",
    name: "Heu-Man-Links",
    projectType: "Digital Service",
    image: "/project3.jpg",
    color: "#b1b1b3",
  },
];
